[package]
name = "ganlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.6"
noodles-gtf = "0.10.0"
noodles-gff = "0.12.0"
bio = "1.3.1"
